train:
  train_all_llama_mixed_sea: 1.0
valid:
  valid_all_llama_mixed_sea: 1.0
  valid_en_llama_mixed_sea: 1.0
  valid_id_llama_mixed_sea: 1.0
  valid_vi_llama_mixed_sea: 1.0
  valid_th_llama_mixed_sea: 1.0
  valid_ms_llama_mixed_sea: 1.0
