train:
  train_data_mixture_en_redpajama: 0.11626259437685464
  train_data_mixture_cleaned_cc100_ind_dedup: 0.3023324727673028
  train_data_mixture_cleaned_cc100_th_dedup: 0.07255505973716814
  train_data_mixture_cleaned_cc100_vi_dedup: 0.5088498731186746
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00022400617785296858
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
