train:
  train_data_mixture_en_redpajama: 0.15893793769721962
  train_data_mixture_cleaned_cc100_ind_dedup: 0.15892358661906544
  train_data_mixture_cleaned_cc100_th_dedup: 0.10066815931536115
  train_data_mixture_cleaned_cc100_vi_dedup: 0.5814703163683538
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 1.684821663948377e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 208
model_name: tiny_LLaMA_mistral_120M
