train:
  train_data_mixture_en_redpajama: 0.25954567104876985
  train_data_mixture_cleaned_cc100_ind_dedup: 0.2985225807185164
  train_data_mixture_cleaned_cc100_th_dedup: 0.04799181493445845
  train_data_mixture_cleaned_cc100_vi_dedup: 0.39393993329825533
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 1.1182715405555885e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 240
model_name: tiny_LLaMA_mistral_120M
