train:
  train_data_mixture_en_redpajama: 0.38988562035637686
  train_data_mixture_cleaned_cc100_ind_dedup: 0.1351481873120702
  train_data_mixture_cleaned_cc100_th_dedup: 0.2174708847790163
  train_data_mixture_cleaned_cc100_vi_dedup: 0.2574953075525367
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 3.1743524774970716e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 224
model_name: tiny_LLaMA_mistral_120M
