train:
  train_data_mixture_en_redpajama: 0.16832161489108838
  train_data_mixture_cleaned_cc100_ind_dedup: 0.3520474675502855
  train_data_mixture_cleaned_cc100_th_dedup: 0.1924082919643467
  train_data_mixture_cleaned_cc100_vi_dedup: 0.28722262559427947
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.0002798391271001504
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
