train:
  train_data_mixture_en_redpajama: 0.2765822351530917
  train_data_mixture_cleaned_cc100_ind_dedup: 0.2648220502082329
  train_data_mixture_cleaned_cc100_th_dedup: 0.18665333679194962
  train_data_mixture_cleaned_cc100_vi_dedup: 0.2719423778467257
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 7.479126939682158e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 112
model_name: tiny_LLaMA_mistral_120M
