train:
  train_data_mixture_en_redpajama: 0.18154407536963516
  train_data_mixture_cleaned_cc100_ind_dedup: 0.2793090294943793
  train_data_mixture_cleaned_cc100_th_dedup: 0.14219336928293266
  train_data_mixture_cleaned_cc100_vi_dedup: 0.396953525853053
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 1.1607259571603902e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 240
model_name: tiny_LLaMA_mistral_120M
