train:
  train_data_mixture_en_redpajama: 0.04317682300312966
  train_data_mixture_cleaned_cc100_ind_dedup: 0.34301081386420945
  train_data_mixture_cleaned_cc100_th_dedup: 0.30280632489073966
  train_data_mixture_cleaned_cc100_vi_dedup: 0.31100603824192125
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 2.946390465601363e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 240
model_name: tiny_LLaMA_mistral_120M
