train:
  train_data_mixture_en_redpajama: 0.20802852838798574
  train_data_mixture_cleaned_cc100_ind_dedup: 0.3184724232275823
  train_data_mixture_cleaned_cc100_th_dedup: 0.2719880949496875
  train_data_mixture_cleaned_cc100_vi_dedup: 0.20151095343474448
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 3.684553317807244e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 256
model_name: tiny_LLaMA_mistral_120M
