train:
  train_data_mixture_en_redpajama: 0.37795951611057044
  train_data_mixture_cleaned_cc100_ind_dedup: 0.08464776624376029
  train_data_mixture_cleaned_cc100_th_dedup: 0.3860880530197054
  train_data_mixture_cleaned_cc100_vi_dedup: 0.15130466462596384
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 1.8840881177049814e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 80
model_name: tiny_LLaMA_mistral_120M
