train:
  train_data_mixture_en_redpajama: 0.22522525168866414
  train_data_mixture_cleaned_cc100_ind_dedup: 0.10133285448633743
  train_data_mixture_cleaned_cc100_th_dedup: 0.3700092051111485
  train_data_mixture_cleaned_cc100_vi_dedup: 0.30343268871384976
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.0001635617737448073
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 288
model_name: tiny_LLaMA_mistral_120M
