train:
  train_data_mixture_en_redpajama: 0.2182518695588272
  train_data_mixture_cleaned_cc100_ind_dedup: 0.16701596332103172
  train_data_mixture_cleaned_cc100_th_dedup: 0.4104211265129652
  train_data_mixture_cleaned_cc100_vi_dedup: 0.20431104060717592
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00037127451806165564
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 224
model_name: tiny_LLaMA_mistral_120M
