train:
  train_data_mixture_en_redpajama: 0.1724397260640287
  train_data_mixture_cleaned_cc100_ind_dedup: 0.17824132450890104
  train_data_mixture_cleaned_cc100_th_dedup: 0.34346201057670867
  train_data_mixture_cleaned_cc100_vi_dedup: 0.3058569388503616
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.0002287302628240756
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 272
model_name: tiny_LLaMA_mistral_120M
