train:
  train_data_mixture_en_redpajama: 0.41481150188005
  train_data_mixture_cleaned_cc100_ind_dedup: 0.352514372295443
  train_data_mixture_cleaned_cc100_th_dedup: 0.08935056312552166
  train_data_mixture_cleaned_cc100_vi_dedup: 0.14332356269898536
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00027557241979907416
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 32
model_name: tiny_LLaMA_mistral_120M
