train:
  train_data_mixture_en_redpajama: 0.5001895263440312
  train_data_mixture_cleaned_cc100_ind_dedup: 0.10495797763999433
  train_data_mixture_cleaned_cc100_th_dedup: 0.26618580312844026
  train_data_mixture_cleaned_cc100_vi_dedup: 0.12866669288753427
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.0003411971300927294
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
