train:
  train_data_mixture_en_redpajama: 0.07365621520874707
  train_data_mixture_cleaned_cc100_ind_dedup: 0.38627396856976043
  train_data_mixture_cleaned_cc100_th_dedup: 0.21985569281395984
  train_data_mixture_cleaned_cc100_vi_dedup: 0.32021412340753275
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00010515596091784259
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
