train:
  train_data_mixture_en_redpajama: 0.07371292488299014
  train_data_mixture_cleaned_cc100_ind_dedup: 0.38825803779781043
  train_data_mixture_cleaned_cc100_th_dedup: 0.32998340859954434
  train_data_mixture_cleaned_cc100_vi_dedup: 0.2080456287196552
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00023499251500428006
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
