train:
  train_data_mixture_en_redpajama: 0.10653711744129056
  train_data_mixture_cleaned_cc100_ind_dedup: 0.20697347617884254
  train_data_mixture_cleaned_cc100_th_dedup: 0.48616352674446234
  train_data_mixture_cleaned_cc100_vi_dedup: 0.2003258796354045
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00020208190058935692
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
