train:
  train_data_mixture_en_redpajama: 0.2753980044948762
  train_data_mixture_cleaned_cc100_ind_dedup: 0.3068615715232943
  train_data_mixture_cleaned_cc100_th_dedup: 0.12262380265704685
  train_data_mixture_cleaned_cc100_vi_dedup: 0.29511662132478256
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 7.907316496874909e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
