train:
  train_data_mixture_en_redpajama: 0.10728018736205919
  train_data_mixture_cleaned_cc100_ind_dedup: 0.5041260418586401
  train_data_mixture_cleaned_cc100_th_dedup: 0.23005542985737623
  train_data_mixture_cleaned_cc100_vi_dedup: 0.1585383409219245
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.0003820321450310091
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
