train:
  train_data_mixture_en_redpajama: 0.15664393600507473
  train_data_mixture_cleaned_cc100_ind_dedup: 0.34248551736386573
  train_data_mixture_cleaned_cc100_th_dedup: 0.2719385555079154
  train_data_mixture_cleaned_cc100_vi_dedup: 0.22893199112314408
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00020453910747870435
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
