train:
  train_data_mixture_en_redpajama: 0.21090839522824611
  train_data_mixture_cleaned_cc100_ind_dedup: 0.10592133655790777
  train_data_mixture_cleaned_cc100_th_dedup: 0.40349943839187236
  train_data_mixture_cleaned_cc100_vi_dedup: 0.2796708298219738
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.0002464271063020725
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
