train:
  train_data_mixture_en_redpajama: 0.23636498738431613
  train_data_mixture_cleaned_cc100_ind_dedup: 0.3735154156761785
  train_data_mixture_cleaned_cc100_th_dedup: 0.12951536640052227
  train_data_mixture_cleaned_cc100_vi_dedup: 0.260604230538983
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 4.957390171775252e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
