train:
  train_data_mixture_en_redpajama: 0.17730023829239347
  train_data_mixture_cleaned_cc100_ind_dedup: 0.29568031165643505
  train_data_mixture_cleaned_cc100_th_dedup: 0.113981441892185
  train_data_mixture_cleaned_cc100_vi_dedup: 0.41303800815898656
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.000265493153248023
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
