train:
  train_data_mixture_en_redpajama: 0.07495904831381638
  train_data_mixture_cleaned_cc100_ind_dedup: 0.4433055628478531
  train_data_mixture_cleaned_cc100_th_dedup: 0.356645967244901
  train_data_mixture_cleaned_cc100_vi_dedup: 0.12508942159342956
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 2.734799250344007e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
