train:
  train_data_mixture_en_redpajama: 0.3681208035538145
  train_data_mixture_cleaned_cc100_ind_dedup: 0.13023940957249927
  train_data_mixture_cleaned_cc100_th_dedup: 0.18845295677297874
  train_data_mixture_cleaned_cc100_vi_dedup: 0.3131868301007075
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.0003198640607382855
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
