train:
  train_data_mixture_en_redpajama: 0.2829758724004597
  train_data_mixture_cleaned_cc100_ind_dedup: 0.15658654942615488
  train_data_mixture_cleaned_cc100_th_dedup: 0.33371973516392417
  train_data_mixture_cleaned_cc100_vi_dedup: 0.22671784300946127
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 8.363694804849154e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
