train:
  train_data_mixture_en_redpajama: 0.28228179105400136
  train_data_mixture_cleaned_cc100_ind_dedup: 0.24930834625190446
  train_data_mixture_cleaned_cc100_th_dedup: 0.20192277167340716
  train_data_mixture_cleaned_cc100_vi_dedup: 0.266487091020687
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 0.00034461191940478655
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
