train:
  train_data_mixture_en_redpajama: 0.20985072745359892
  train_data_mixture_cleaned_cc100_ind_dedup: 0.27122609531245523
  train_data_mixture_cleaned_cc100_th_dedup: 0.15815908876189397
  train_data_mixture_cleaned_cc100_vi_dedup: 0.36076408847205177
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 2.0298598756967223e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
