train:
  train_data_mixture_en_redpajama: 0.3112018017990245
  train_data_mixture_cleaned_cc100_ind_dedup: 0.16858659886459762
  train_data_mixture_cleaned_cc100_th_dedup: 0.37765619098386916
  train_data_mixture_cleaned_cc100_vi_dedup: 0.14255540835250866
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 8.681216775786634e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
