train:
  train_data_mixture_en_redpajama: 0.3793893582546067
  train_data_mixture_cleaned_cc100_ind_dedup: 0.2791282125912535
  train_data_mixture_cleaned_cc100_th_dedup: 0.1688321734566394
  train_data_mixture_cleaned_cc100_vi_dedup: 0.17265025569750048
valid:
  valid_data_mixture_en_redpajama: 1.0
  valid_data_mixture_id_wikipedia: 1.0
  valid_data_mixture_th_wikipedia: 1.0
  valid_data_mixture_vi_wikipedia: 1.0
learning_rate: 5.5512592663587755e-05
warmup_steps: 0
total_steps: 10000
decay_lr: false
global_batch_size: 128
model_name: tiny_LLaMA_mistral_120M
